version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=businessrule
      - POSTGRES_USER=businessruleuser
      - POSTGRES_PASSWORD=businessrulepassword
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  postgres-data: