server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/businessrule
    driverClassName: org.postgresql.Driver
    username: businessruleuser
    password: businessrulepassword

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate